server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6up8c7gi27c73eiffgg-a.singapore-postgres.render.com:5432/chess_db_4wbg?sslmode=require
spring.datasource.username=chess_db_4wbg_user
spring.datasource.password=56eOu31FN06ia642BKtPeR680dto2NOU
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect